import './globals.css'
import { Inter } from 'next/font/google'
import Providers  from './Providers'
import { Spinner } from 'flowbite-react';
const inter = Inter({ subsets: ['latin'] })
import Loading from '@/components/Spinner';
import dynamic from 'next/dynamic';
const Slidebar = dynamic(() => import('@/components/Sidebar'), { ssr: false, loading: () => <Loading/> })
export const metadata = {
  title: 'Casa Ces´s',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}><Providers><div className='flex flex-col md:flex-row  h-screen gap-3'><Slidebar/>{children}</div></Providers></body>
    </html>
  )
}
