import './globals.css'
import { Inter } from 'next/font/google'
import Providers  from './Providers'
const inter = Inter({ subsets: ['latin'] })
import Slidebar from '@/components/Sidebar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}><Providers><Slidebar/>{children}</Providers></body>
    </html>
  )
}
